version: '3'

services:
  db:
    container_name: db
    restart: unless-stopped
    image: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
